import type { CSSProperties } from 'react';
import type { Theme, ThemeId } from './types';

export const THEMES: Record<ThemeId, Theme> = {
  observatory: {
    id: 'observatory',
    label: 'Observatory',
    tokens: {
      background: '#071416',
      surface: '#102427',
      ink: '#f3ecd8',
      muted: '#9dafaa',
      faint: '#46605d',
      line: '#6c7c72',
      accent: '#d8b96a',
      accentAlt: '#e77f67',
      warm: '#efb45e',
      cool: '#8ac1ca',
      displayFont: "'Newsreader Variable', serif",
      bodyFont: "'Space Grotesk Variable', sans-serif",
      glow: true,
    },
    seasons: {
      winter: '#31516b',
      spring: '#668f72',
      summer: '#b6753a',
      autumn: '#8f5142',
    },
    temperatureStops: [
      [0, '#8b5fd3'],
      [30, '#dcecf1'],
      [50, '#367eb0'],
      [75, '#55a66f'],
      [100, '#f14f43'],
    ],
    backdrop: 'stars',
    precipTexture: 'streak',
    ambience: 'celestial',
  },
  editorial: {
    id: 'editorial',
    label: 'Editorial',
    tokens: {
      background: '#f4f3ef',
      surface: '#ffffff',
      ink: '#181c1b',
      muted: '#676e6b',
      faint: '#c4c7c1',
      line: '#929791',
      accent: '#d43d32',
      accentAlt: '#137b77',
      warm: '#d49a22',
      cool: '#3977a8',
      displayFont: "'Newsreader Variable', serif",
      bodyFont: "'Space Grotesk Variable', sans-serif",
      glow: false,
    },
    seasons: {
      winter: '#9eb9ce',
      spring: '#82a86f',
      summer: '#dfb33e',
      autumn: '#c7674f',
    },
    temperatureStops: [
      [0, '#7652a8'],
      [30, '#c9e0e8'],
      [50, '#397eb0'],
      [75, '#4c9464'],
      [100, '#d63e35'],
    ],
    backdrop: 'print',
    precipTexture: 'stipple',
    ambience: null,
  },
  almanac: {
    id: 'almanac',
    label: 'Almanac',
    tokens: {
      background: '#e9e6d7',
      surface: '#f6f1dc',
      ink: '#173f3a',
      muted: '#60766d',
      faint: '#b7b69f',
      line: '#77877a',
      accent: '#c83f49',
      accentAlt: '#167984',
      warm: '#e2a624',
      cool: '#4c83a2',
      displayFont: "'Fraunces Variable', serif",
      bodyFont: "'Space Grotesk Variable', sans-serif",
      glow: false,
    },
    seasons: {
      winter: '#6f9aae',
      spring: '#73a86f',
      summer: '#e4b52c',
      autumn: '#bd5945',
    },
    temperatureStops: [
      [0, '#7f5ca4'],
      [30, '#d7e5df'],
      [50, '#4282a6'],
      [75, '#659c58'],
      [100, '#cf413d'],
    ],
    backdrop: 'paper',
    precipTexture: 'hatch',
    ambience: 'seasonal',
  },
};

export const THEME_ORDER: ThemeId[] = ['observatory', 'editorial', 'almanac'];

export function themeCssProperties(theme: Theme): CSSProperties {
  return {
    '--background': theme.tokens.background,
    '--surface': theme.tokens.surface,
    '--ink': theme.tokens.ink,
    '--muted': theme.tokens.muted,
    '--faint': theme.tokens.faint,
    '--line': theme.tokens.line,
    '--accent': theme.tokens.accent,
    '--accent-alt': theme.tokens.accentAlt,
    '--warm': theme.tokens.warm,
    '--cool': theme.tokens.cool,
    '--display-font': theme.tokens.displayFont,
    '--body-font': theme.tokens.bodyFont,
  } as CSSProperties;
}